import sqlite3
import pandas as pd
import re
import collections
from sqlalchemy import create_engine
import mysql.connector
import glob
import time


def create_db():
    db = 'ig_list.db'
    conn = sqlite3.connect(db)
    cur = conn.cursor()

    sql = '''CREATE TABLE IF NOT EXISTS hashtag(
    id TEXT PRIMARY KEY,
    hashtag1 TEXT,
    hashtag2 TEXT,
    hashtag3 TEXT,
    hashtag4 TEXT,
    hashtag5 TEXT,
    hashtag6 TEXT,
    hashtag7 TEXT,
    hashtag8 TEXT,
    hashtag9 TEXT,
    hashtag10 TEXT,
    hashtag11 TEXT,
    hashtag12 TEXT,
    hashtag13 TEXT,
    hashtag14 TEXT,
    hashtag15 TEXT,
    hashtag16 TEXT,
    hashtag17 TEXT,
    hashtag18 TEXT,
    hashtag19 TEXT,
    hashtag20 TEXT,
    hashtag21 TEXT,
    hashtag22 TEXT,
    hashtag23 TEXT,
    hashtag24 TEXT,
    hashtag25 TEXT,
    hashtag26 TEXT,
    hashtag27 TEXT,
    hashtag28 TEXT,
    hashtag29 TEXT,
    hashtag30 TEXT)'''
    cur.execute(sql)
    conn.commit()
    conn.close()

def insert():
    db = 'ig_list.db'
    conn = sqlite3.connect(db)
    cur = conn.cursor()

    sql = '''
    INSERT into hashtag (id,
    hashtag1,
    hashtag2,
    hashtag3,
    hashtag4,
    hashtag5,
    hashtag6,
    hashtag7,
    hashtag8,
    hashtag9,
    hashtag10,
    hashtag11,
    hashtag12,
    hashtag13,
    hashtag14,
    hashtag15,
    hashtag16,
    hashtag17,
    hashtag18,
    hashtag19,
    hashtag20,
    hashtag21,
    hashtag22,
    hashtag23,
    hashtag24,
    hashtag25,
    hashtag26,
    hashtag27,
    hashtag28,
    hashtag29,
    hashtag30) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    '''

    cur.execute(sql,params)
    conn.commit()
    conn.close()

def insert_mysql():
    engine = create_engine('mysql+mysqlconnector://b58325833839d0:f0fb916b@us-cdbr-east-06.cleardb.net/heroku_dd21f3af32a652e', echo=True)
    df.to_sql('hashtag',engine, if_exists='append', index=False)


user_list = [
'ayami.0624',
'ayami_yamichan',
'ayannu61',
'ayaokutsu',
'ayapan_beauty',
'aza_mote.gram',
'azu_cosmeotaku',
'azu_k02',
'azuayu',
'bamli.tokyo',
'bb_jp_nakamu',
'beauty_mentalist_yuya',
'beauty_mmr',
'beautyurigram',
'before_after89',
'berry.3b',
'bihada.ni.naru',
'bihada_care_channel',
'bihada_katu',
'bihada_maniac',
'bitan__channel',
'biyo_nurse',
'biyou.bot.kotono',
'biyou.nurse.chicchi',
'biyou_hifuko',
'biyouiryou_media',
'biyoushin_413',
'blube_cosme',
'blue_mayu_',
'bluebase_winter8',
'bluebe_chan',
'bluebe_matome',
'bm_krh',
'borotama9',
'brg_magazine',
'bubblism0310',
'buruchan.1.7',
'bytheharu',
'cc_chihiro_yakugaku',
'chachakun_cosme',
'chan____ara',
'chanmaai8888vlog',
'chanmaru_cosme_',
'chansan_makeup',
'charico2019',
'charmix2020',
'cherie_latte_official',
'chi.cosme07',
'chicchimity',
'chieru_40biyo',
'chiiko_22111',
'chika24rgrm',
'china___makeup',
'chon_._._',
'cjmrm_f',
'ckumacom',
'clear.skin_beauty',
'clearocean_n',
'coco_home__',
'cocoa.x2',
'cocoasa01',
'cocon_makeup',
'coslabo39',
'cosm_e.kore_a',
'cosmate_2021',
'cosme.ai777',
'cosme__roa',
'cosme_akmemo',
'cosme_bunny_ch',
'cosme_otaku01',
'cosme_room_',
'cosmelog_official',
'cosmelove.korea',
'cosmelovelove',
'cosmenprotein',
'cosmesalan',
'coszakka',
'cotoha.bihada.labo',
'dayday_blog',
'ditea_inc',
'dngnchan',
'ebichan_nn_n',
'eimy_official',
'eina_makeup',
'ema_kamakulife',
'emiii.1230',
'emirin_style',
'emizu1113',
'emme_cosme',
'emu_1107',
'enukosme_biyo',
'esute_tsukuba',
'eye__pallet',
'fcl_skincare',
'fuchan_2003',
'gaho_gaho_gaho',
'h1t0mi_0210',
'h_beauty333888',
'haaaxxcosme',
'haana0424',
'haasan_haru',
'haccipocchixx',
'hana.chocolate.taku',
'hana.cosme33',
'hana___skin',
'hani_korea.cosme',
'happy_cosme3150',
'harue_beautycreate',
'haruka_naturalmake',
'harupon.15',
'hashiyuuui',
'hau_beauty_room',
'hayato.yamada',
'hii_chachacha',
'hikaru_0177',
'hima323232',
'hima_990830',
'hinano___days',
'hiromix_by_aphrodite',
'hitomi1218',
'hiyo_101211',
'homcos_beauty_',
'hondayuni022',
'honey_chiaki07',
'hoppe240',
'hp7nk_rika',
'hukusuke831',
'hystericm8n',
'i.k.1986',
'ichrin_2020',
'iebe_chan',
'iebe_cosme',
'iebe_joshi',
'iebe_lab',
'innar_care',
'io_aoyama',
'itomisuzu_',
'iwbcd___6',
'izayoi.mion',
'k__n__k__n__',
'kah0_cosme_insta',
'kaho.skincare',
'kajinyos7',
'kamicosme_trend',
'kanae_skin07',
'kanan_cosme',
'kaorigram61',
'kaotiinu',
'kaoyase_fight',
'karako_cosme',
'karin__life',
'karinnn000',
'kasumi_liver',
'keana_method',
'keana_nara',
'kei_marunouchi.ol',
'keko_blog',
'kenbihada_second',
'keshouhinko1225',
'kii.beauty_',
'kii_kurashi_',
'kisumi0315',
'kmk93ko',
'kmr_119',
'knk_csmpink',
'kobamo___cc',
'koharu_kurashi',
'kohinata_moke',
'kokkofk',
'komekichiiii',
'kooki_mensskincare',
'korea_yura',
'ktmk___55',
'kuma_chika888',
'kurumi_hanji',
'kuucosme',
'kyanon_beauty',
'kyuru_kyurumi',
'laluminariste',
'lana__cosme',
'lavi8d_gray',
'leina810',
'lemonchan_0408',
'lily_70626',
'lisa.1656',
'love_miyuka',
'luuna_cosme_',
'luvu_cosme',
'm___22___y',
'm_loves_kcosme',
'm_y_i.30',
'ma.yu8980',
'maco.0624',
'maho_713',
'maimai.007',
'maimero.iciigomilk.y',
'make.i__grow',
'make_up_hitoe',
'maki_color_',
'makiiiy_makeup',
'mami_beautycosme',
'manami__beauty',
'marc.i3',
'mari_fasting',
'maripii_cosme',
'maru959595959595',
'mashimarooooo3',
'matakichi_38',
'may_runa_69',
'mayday_kr',
'mayu__skincare',
'mayu_cosme_',
'mayusaaaaaaaaan',
'mcendo1027_beauty',
'me_cos_me',
'meg.948',
'megumi_bihada',
'meili_diary',
'melt__make',
'mens___ichi',
'mens_beauty_ren',
'mens_bihada_yuma',
'mens_biyou_hozu',
'mens_biyou_puchipura',
'mens_makeup1',
'mens_skincare_takkun',
'mens_smart',
'mensbeauty_cosme_d',
'mensbiyou_info',
'menscosme_23',
'mente_rugi',
'meru_cosme',
'mighty_cosme',
'mii___0228',
'mii__makeup__',
'mii_atlanta',
'mikako110403',
'miki_kurasi',
'mikichi0726',
'miku_cosmake',
'millerje_0331',
'mimiovomimi',
'mimitan090909',
'minamininaritaiol',
'mink__88',
'mint_beautylab',
'miomio.bikatsu',
'mirimanialove',
'mirin_biyou',
'misamisa_714',
'misianomakeup',
'misora_cosmetics',
'mitan.m',
'mite_beauty',
'mito_makeup',
'miyuki_beautylog',
'miyupon.cosme',
'mizumoto_kahogram',
'mk_____ch',
'mmk.87_',
'mmmaruu_20',
'mo.mo.mama',
'moka.3o',
'moku_hico',
'momo___channn',
'momo___cosme',
'momo_suppinbeauty',
'momochan_kakei',
'momomi_makino',
'momomo1572',
'momoringo_5',
'moomie_official',
'mote__cosme',
'mote_bunseki',
'mote_csm',
'mrmrmron7',
'msyui313',
'mu_1922',
'murasaki_miku',
'mwnail.kt',
'myao_myao_25',
'myme_dlaw',
'n_h2ka',
'na.na1557',
'na_chan_beauty',
'nachaaaaki',
'nagaonaga',
'nagi_30life_',
'naka_6519csm',
'nako__make',
'namekochaaaan',
'namu6331',
'nana198612',
'nanamin_skincare',
'nanas.cosme',
'nao__nao__705',
'naooo__228',
'natsum10803',
'naturee.media',
'navi_cosbeauty',
'naxana_chan',
'nenbi_cosme',
'nene_cosme_nene',
'nera.beauty',
'niinana27',
'nishoku_a34',
'noa_beauty_diet',
'noako_cosme',
'non_chan______',
'nuusan_beauty',
'nynn77',
'o_bury_',
'oimothan_01',
'ol__milktea___',
'omi_cosme_beauty',
'ossy_beautylog',
'otojo.style',
'otona.danshi_labo',
'otona_cosme_channel',
'otona_no_cosme',
'pamyuiri',
'pickmi.beauty',
'piii_xx_01',
'pink___yuri',
'pinkcandy_8',
'pinkposs1989',
'pipi_lilly',
'pocoapoco_jp',
'pomemama_biyou',
'princess19851228',
'puchipuracosme_ranking',
'purple000211',
'r21.cosme',
'rabichannn',
'ranran_ol',
'rapunze.luna',
'real_chan_cosme',
'reina_30s',
'rena_cosme_',
'rena_inmybag',
'rena_rena.biyou',
'rere_cosme_biyou',
'rikoniko.cosme',
'rily.cosme',
'rina072116',
'rincos_room',
'rinrin934',
'rio6688reia',
'rise_n0910',
'risu_cyoukatsu',
'roomuji_yume',
'rosegirl.diary',
'ruluu112t',
'rurero_cosme',
'ruru_hitoe_okubutae',
'ruu_beautylife',
'ryoko_makeup',
's__spring241',
'sa_e._',
'saa_ya06',
'sachi.nail_',
'sachio_biyou',
'saesaesaeko03',
'saikyou_naritai',
'sakiiiii20',
'sakura__cosme',
'sakurako_cosme',
'saori000917',
'sara_sancsm',
'sari_pink144',
'sasss0421',
'schk_maru',
'seira_brube',
'sekiyumiko0821',
'serababy_',
'shi0tann',
'shihosan_star',
'shimakyo_cosme',
'shiro_tuki1',
'shk.2727',
'shushu_223_',
'siki_aoi',
'siratama.cosme',
'skin_care_remind',
'skincare.media.bihada',
'skincare.selegram',
'skincare_8_',
'skincare_fuchan',
'skincare_kasumi',
'skincare_kira',
'skincare_maniac_',
'skincare_prk',
'skincare_repo_',
'sklabo14130',
'skrrika152',
'smilesss_beauty',
'soa_channel',
'sou_mensbiyou',
'sssyk_25',
'su_beauty_life',
'su_cosme_',
'sugar_moon_lala',
'sui__33',
'summer_zyoshi',
't_h_h_t',
'tackey_mens_skincare',
'tantaline15',
'tapi1543',
'tarako___v',
'tawamurecham',
'tenko0517',
'thenight_is_beauty',
'tiara7_momo',
'to_mysweets',
'tomato4researcher',
'tomo__happylife',
'tomoko_cosme',
'tomomin_iebe',
'tsukiko_kotsuki',
'tsumiki_beauty',
'tsuruas',
'u15_ui12',
'umino_yuki',
'unico.ousia',
'urico.sme',
'usacosme',
'usayoshi_cosme',
'wabu001',
'wannyan_29',
'watao_akanuke',
'welcome.baby1122',
'welcomecherry',
'woman_from30',
'x.x.pixk.x.x',
'x_xx_mari_xx_x',
'xiaodaoxinghui13',
'xoxo_yuuuuu_xoxo',
'y_miyong_',
'y_n_a79',
'ya_o9o3',
'yapoi114',
'yayopi037',
'yo_shi_no_n_',
'yoppi_skin',
'yoppy__0206',
'yoriko_makeup',
'yu11_m',
'yua_style_',
'yui_cool.make',
'yuka_mamabiyou',
'yukarii_32beauty',
'yuki_lifetravel',
'yuki_mens_beauty',
'yukina_skincare',
'yuko.love.beauty_yummy',
'yumi.ma.ma',
'yuri.littlebylittle',
'yuriko1207yz',
'yurikocosme',
'yuta_menbeauty',
'yuu_cosmelife',
'yuu_cosmelife2',
'yuu_mens_beauty',
'yuuki_beauty',
'yuuri_ftb',
'yuuriofficial',
'yuusan0600'
]


for id in user_list:
    try:
        # SELECT文を実行してデータを取得し、DataFrameに格納する
        engine = create_engine('mysql+mysqlconnector://b58325833839d0:f0fb916b@us-cdbr-east-06.cleardb.net/heroku_dd21f3af32a652e', echo=True)
        df = pd.read_sql_query(f"SELECT caption FROM post_detail WHERE id = '{id}'", engine)
        print(df)
        #空の文字列を作成
        txt = ''
        #dfの長さだけFor loopですべてのキャプションを1つも文字列に渡す
        for i in range(0,242):
            txt = txt + str(df.iloc[i,0])
        #正規表現で#がついたものだけ抽出
        tags = re.findall(r"#\S*",txt)
        #ハッシュタグの数の多い30個を抽出
        tag_count = collections.Counter(tags)
        tag_count =tag_count.most_common(30)
        df2= pd.DataFrame(tag_count)
        params = []
        params.append(id)
        #dfの長さだけFor loopですべてのキャプションを1つも文字列に渡す
        for i in range(0,30):
            a = df2.iloc[i,0]
            params.append(a)

        df = pd.DataFrame([params], columns=['id',
        'hashtag1',
        'hashtag2',
        'hashtag3',
        'hashtag4',
        'hashtag5',
        'hashtag6',
        'hashtag7',
        'hashtag8',
        'hashtag9',
        'hashtag10',
        'hashtag11',
        'hashtag12',
        'hashtag13',
        'hashtag14',
        'hashtag15',
        'hashtag16',
        'hashtag17',
        'hashtag18',
        'hashtag19',
        'hashtag20',
        'hashtag21',
        'hashtag22',
        'hashtag23',
        'hashtag24',
        'hashtag25',
        'hashtag26',
        'hashtag27',
        'hashtag28',
        'hashtag29',
        'hashtag30'])
        print(df)
        insert_mysql()
        print('Successfully Executed'+': '+id)
        time.sleep(5)
    except Exception as e:
        print(e)
        print('No Data'+': '+id)
        time.sleep(5)

#create_db()
